# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "active_merchant_payline_gateway"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fran\u{e7}ois Turbelin"]
  s.date = "2013-02-14"
  s.description = "That gem allows to make the basics of epayment. It is also allowing to manage recurring payment."
  s.email = "pacodelaluna@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "active_merchant_payline_gateway.gemspec",
    "lib/active_merchant/billing/integrations/payline/helper.rb",
    "lib/active_merchant/billing/integrations/payline/notification.rb",
    "lib/active_merchant/billing/integrations/payline/return.rb",
    "lib/active_merchant/billing/payline_gateway.rb",
    "lib/active_merchant_payline_gateway.rb",
    "test/helper.rb",
    "test/test_active_merchant_payline_gateway.rb"
  ]
  s.homepage = "http://github.com/pacodelaluna/active_merchant_payline_gateway"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "ActiveMerchant Gateway for Payline payment"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

